### ISSUE TITLE
Chunked transfer encoding

### ISSUE THREAD

**Issue by mauricioabreu** [leandromoreira/resty-bakery#1]
Hello @leandromoreira 

I see you are removing the `Transfer-Encoding` header because some clients have problems supporting this HTTP 1.1 feature

Could it be replaced by [chunked_transfer_encoding directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#chunked_transfer_encoding)?

**Comment by leandromoreira** [comment]
I think if you only use the directive it doesn't work... (I'm sure I tested it) this transfer encoding shouldn't be a problem for most of the client though. (I actually only notice a single client that wasn't able do deal with it)

**Comment by mauricioabreu** [comment]
It worked in my local testes but I just have noticed that `chunked_transfer_encoding` is not dynamic.
